### ISSUE TITLE
Hide mouse cursor

### ISSUE THREAD

**Issue by Pitros** [zehfernandes/rpi-webapplication#3]
Hi.

Is there any fast way to hide mouse cursor, while still using qtbrowser command?

**Comment by zehfernandes** [comment]
The fast way is not plug the mouse in RPI :)

or you can do with CSS

``` css
* {cursor: none;}
```

**Comment by Pitros** [comment]
I've tried hiding it using CSS, but it's still visible, probably QTWebkit doesn't respect that CSS setting.

But anyway finally my RPI will work without mouse, so I guess that should work as well. I'll check that later to be sure. Thanks.
